### PR TITLE
Modified fig:append behaviour

### PR DESCRIPTION
**Pull request by tboloo**
I have modified the behaviour of `fig:plug` combined with `fig:append` to append content to slot, instead of overwriting it. So, one can now define some default content, e.g.:
```xml
<fig:template>
<slot fig:slot="myslot">The default</slot>
...
<plug fig:plug="myslot" fig:append="true" fig:mute="true">: content</plug>
</fig:template>
```
would render as follows:
```xml
<slot>The default: content</slot>
```
instead of:
```
<slot>: content</slot>
```
If you find it aligned with your philosophy for FigDice - please accept and merge.

### CODE REVIEW

**Comment by gabrielzerbib** [comment]
Hi Bolek,

I love the idea. However I see two issues, for which I would like to know your opinion:

- **1** This way of using the append option on `fig:plug`, contradicts the assertion that the slot tag (the tag on which the `fig:slot` directive is declared) is mute *de facto*.
Normally (although it is not yet properly documented in the [Wiki](https://github.com/gabrielzerbib/figdice/wiki/fig:slot) -- but written in the [comments](https://github.com/gabrielzerbib/figdice/blob/master/src/figdice/classes/ViewElementTag.php#L528)), a `fig:slot` directive absorbs the holding tag.

This is illustrated in the following piece of template:

~~~~xml
<fig:template>
  <!-- default content for the slot -->
  <span><slot fig:slot="myslot">Hello, </slot></span>

  <!-- plug: we use append to engage your feature and concatenate with default -->
  <fig:mute fig:plug="myslot" fig:append="true">Bolek</fig:mute>
</fig:template>
~~~~

Using your patch, it will render as:

~~~~xml
<span><slot>Hello, </slot>Bolek</span>
~~~~

therefore suppressing the auto-muting effect of a `fig:slot` attribute.

There is, of course, a workaround: we could force a tag that carries a `fig:slot` directive to be mute.

--- 

- **2** The way you achieve the append, will repeat the default contents in case we append more than once. This is illustrated in the following piece of template: (this time I intentionally mute the `fig:slot` tag so that it won't interfere in the result, despite the above bullet-point)

~~~~xml
<fig:template>
  <!-- default content for the slot -->
  <span><fig:mute fig:slot="myslot">Hello, </fig:mute></span>

  <!-- first plug: we use append to engage your feature and concatenate with default -->
  <fig:mute fig:plug="myslot" fig:append="true">Bolek</fig:mute>
  <!-- second plug: appending again -->
  <fig:mute fig:plug="myslot" fig:append="true">, Gabriel</fig:mute>
</fig:template>
~~~~

It renders into:

~~~~xml
<span>Hello, BolekHello, , Gabriel</span>
~~~~

instead of, supposedly, an expected:

~~~~xml
<span>Hello, Bolek, Gabriel</span>
~~~~

----

In fact, I would probably achieve some default content for a slot, in the following way:

~~~~xml
<span>Hello, <slot fig:slot="users" /></span>
<fig:mute fig:plug="users" fig:append="true">Bolek</fig:mute>
<fig:mute fig:plug="users" fig:append="true">, Gabriel</fig:mute>
~~~~

which renders in: 

~~~~xml
<span>Hello, Bolek, Gabriel</span>
~~~~

My `fig:slot` is on a meaningless tag which gets muted always (as per current behavior of slots&plugs), and it gives you the opportunity to put some contents before the series of appended plugs.

The initial purpose of the plug is, for example, to be able to add stuff to the topmost `<style>` section of the page inside the `<header>`, or to append bottom `<script>`s from any location in the template.

**Comment by tboloo** [comment]
Hi Gabriel,
I am glad that my input got your interest, and thank you very much for your comments. Now, I have slightly adjusted my code, to address some of the problems you raised.
Currently, code reders as expected on subsequent plugs, that is 
```xml
<span>Hello, <slot fig:slot="users" /></span>
<fig:mute fig:plug="users" fig:append="true">Bolek</fig:mute>
<fig:mute fig:plug="users" fig:append="true">, Gabriel</fig:mute>
```
renders as one would expect
```xml
<span>Hello, Bolek, Gabriel</span>
```
(there is of course test for that)

---------------------
As per your other concern, that is the `fig:slot` is de facto mute: now code without `fig:append` would gets replaced entirely, whereas code *with* `fig:append` would retain the original node (which, if needed, could be silenced via `fig:mute`, as you already mentioned). This approach (plug _replaces_, append _retains_), is more natural to me, but that is probably a matter of taste, so I leave this to your decision.

**Comment by gabrielzerbib** [comment]
Hi Bolek,

Thank you, I really do appreciate your contribution. However, I documented the current behavior in the wiki : 
- https://github.com/gabrielzerbib/figdice/wiki/fig:plug 
and
- https://github.com/gabrielzerbib/figdice/wiki/fig:slot

and I think that it explains how to address the use-case that you are trying to achieve. If yes, I might prefer not to change the code or the API.
I invite you to review the explanations there, and please feel free to tell me if you still think that we're missing a case.
Thanks!

**Comment by tboloo** [comment]
Hi Gabriel,
I understand your point, and in the light of your explanations (and updated wiki) there is indeed no need for my modification.
Thank for your feedback, leaving a little bit wiser.
Thanks!

**Pull request closed without merging**
